name: CI Workflow

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          # pip install -r ../requirements.txt
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Build and Start Services
        run: |
          docker-compose -f ${{ github.workspace }}/docker-compose.yml up -d --build \
            --env CLIENT_ID=${{ secrets.CLIENT_ID }} \
            --env CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
            --env REDIRECT_URI=${{ secrets.REDIRECT_URI }} \

      - name: Run tests
        run: |
          # docker-compose -f ${{ github.workspace }}/docker-compose.yml exec app python -m unittest discover -s .. "test_*.py"
          docker-compose -f ${{ github.workspace }}/docker-compose.yml exec app python -m unittest discover -s . -p "test_*.py"

      - name: Stop and remove services
        if: always()
        run: |
          docker-compose -f ${{ github.workspace }}/docker-compose.yml down

      - name: Prune Docker system
        if: always()
        run: |
          docker system prune -f